SET NOCOUNT ON;
GO

-- =============================================================================
-- 7. Bancos — Fix UNIQUE constraint on CUENTANUMERO to allow multiple NULLs
-- =============================================================================

-- Drop the auto-generated UNIQUE constraint that blocks multiple NULL values.
-- SQL Server treats NULL as a value in UNIQUE constraints, so only one NULL is
-- allowed.  We replace it with a filtered unique index that ignores NULLs.

-- Step 1: Drop the existing constraint (name auto-generated by SQL Server)
IF EXISTS (
    SELECT 1
    FROM sys.key_constraints
    WHERE parent_object_id = OBJECT_ID('dbo.Bancos')
      AND name = 'UQ_Bancos__55A059988BC45C0C'
)
BEGIN
    ALTER TABLE dbo.Bancos DROP CONSTRAINT [UQ_Bancos__55A059988BC45C0C];
END;
GO

-- Step 2: Create a filtered unique index that only enforces uniqueness on
-- non-NULL CUENTANUMERO values (multiple NULLs are now allowed)
IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE object_id = OBJECT_ID('dbo.Bancos')
      AND name = 'UQ_Bancos_CuentaNumero'
)
BEGIN
    CREATE UNIQUE INDEX UQ_Bancos_CuentaNumero
        ON dbo.Bancos (CUENTANUMERO)
        WHERE CUENTANUMERO IS NOT NULL;
END;
GO
